/* Kora Utware — service worker (generated by build/4_service_worker.py).
   Precaches the whole app so it runs with no internet at all. */

const CACHE = 'kora-utware-cf7da00986';
/* The app mirrors the licence and trial counters here. It is NOT a
   precache and must survive every upgrade — deleting it would hand a
   paying user back to the paywall. */
const VAULT = 'kora-vault';
const CRITICAL = [
  "index.html",
  "styles.css",
  "app.js",
  "config.js",
  "manifest.webmanifest",
  "data/questions.json",
  "data/unlock.json"
];
const ASSETS = [
  "index.html",
  "styles.css",
  "app.js",
  "config.js",
  "manifest.webmanifest",
  "data/questions.json",
  "data/unlock.json",
  "icons/apple-touch-icon.png",
  "icons/favicon-32.png",
  "icons/icon-192.png",
  "icons/icon-512.png",
  "icons/maskable-512.png",
  "img/q0184_s0.png",
  "img/q0195_o0.png",
  "img/q0195_o1.png",
  "img/q0195_o2.png",
  "img/q0195_o3.png",
  "img/q0199_s0.png",
  "img/q0200_s0.png",
  "img/q0201_s0.png",
  "img/q0204_s0.png",
  "img/q0205_o0.png",
  "img/q0205_o1.png",
  "img/q0205_o2.png",
  "img/q0205_o3.png",
  "img/q0206_o0.png",
  "img/q0206_o1.png",
  "img/q0206_o2.png",
  "img/q0206_o3.png",
  "img/q0207_s0.png",
  "img/q0208_s0.png",
  "img/q0209_s0.png",
  "img/q0210_s0.png",
  "img/q0211_s0.png",
  "img/q0212_s0.png",
  "img/q0213_s0.png",
  "img/q0214_s0.png",
  "img/q0215_s0.png",
  "img/q0216_s0.png",
  "img/q0217_s0.png",
  "img/q0218_s0.png",
  "img/q0219_o0.png",
  "img/q0219_o1.png",
  "img/q0219_o2.png",
  "img/q0219_o3.png",
  "img/q0220_s0.png",
  "img/q0221_s0.png",
  "img/q0222_s0.png",
  "img/q0223_s0.png",
  "img/q0224_s0.png",
  "img/q0225_s0.png",
  "img/q0226_s0.png",
  "img/q0227_s0.png",
  "img/q0228_s0.png",
  "img/q0229_s0.png",
  "img/q0230_s0.png",
  "img/q0231_s0.png",
  "img/q0236_o0.png",
  "img/q0236_o1.png",
  "img/q0236_o2.png",
  "img/q0236_o3.png",
  "img/q0238_s0.png",
  "img/q0239_s0.png",
  "img/q0240_s0.png",
  "img/q0241_s0.png",
  "img/q0242_s0.png",
  "img/q0243_s0.png",
  "img/q0244_s0.png",
  "img/q0245_s0.png",
  "img/q0246_s0.png",
  "img/q0247_s0.png",
  "img/q0248_s0.png",
  "img/q0249_s0.png",
  "img/q0250_s0.png",
  "img/q0251_s0.png",
  "img/q0252_s0.png",
  "img/q0253_s0.png",
  "img/q0254_s0.png",
  "img/q0255_s0.png",
  "img/q0256_s0.png",
  "img/q0257_s0.png",
  "img/q0258_s0.png",
  "img/q0273_s0.png",
  "img/q0274_s0.png",
  "img/q0275_s0.png",
  "img/q0276_s0.png",
  "img/q0277_s0.png",
  "img/q0278_s0.png",
  "img/q0279_s0.png",
  "img/q0280_s0.png",
  "img/q0281_s0.png",
  "img/q0282_s0.png",
  "img/q0283_s0.png",
  "img/q0284_s0.png",
  "img/q0285_s0.png",
  "img/q0286_s0.png",
  "img/q0287_s0.png",
  "img/q0288_s0.png",
  "img/q0294_s0.png",
  "img/q0310_s0.png",
  "img/q0330_s0.png",
  "img/q0336_s0.png",
  "img/q0337_s0.png",
  "img/q0339_s0.png",
  "img/q0340_s0.png",
  "img/q0341_s0.png",
  "img/q0343_s0.png",
  "img/q0344_s0.png",
  "img/q0345_s0.png",
  "img/q0346_s0.png",
  "img/q0357_s0.png",
  "img/q0358_s0.png",
  "img/q0359_s0.png",
  "img/q0360_s0.png",
  "img/q0361_s0.png",
  "img/q0362_s0.png",
  "img/q0363_s0.png",
  "img/q0364_s0.png",
  "img/q0365_s0.png",
  "img/q0366_s0.png",
  "img/q0367_s0.png",
  "img/q0368_s0.png",
  "img/q0369_s0.png",
  "img/q0370_s0.png",
  "img/q0371_s0.png",
  "img/q0372_s0.png",
  "img/q0373_s0.png",
  "img/q0374_s0.png",
  "img/q0375_s0.png",
  "img/q0376_s0.png",
  "img/q0377_s0.png",
  "img/q0378_s0.png",
  "img/q0379_s0.png",
  "img/q0380_s0.png",
  "img/q0381_s0.png",
  "img/q0382_s0.png",
  "img/q0383_s0.png",
  "img/q0384_s0.png",
  "img/q0385_s0.png",
  "img/q0386_s0.png",
  "img/q0387_s0.png",
  "img/q0388_s0.png",
  "img/q0389_s0.png",
  "img/q0390_s0.png",
  "img/q0391_s0.png",
  "img/q0392_s0.png",
  "img/q0393_s0.png",
  "img/q0394_s0.png",
  "img/q0395_s0.png",
  "img/q0396_s0.png",
  "img/q0397_s0.png",
  "img/q0398_s0.png",
  "img/q0399_s0.png",
  "img/q0400_s0.png",
  "img/q0401_s0.png",
  "img/q0402_s0.png",
  "img/q0403_s0.png"
];

/* Fetch in small batches — a cheap phone choking on 150 parallel
   requests is how a precache half-finishes. */
async function fill(cache, urls, strict) {
  const missing = [];
  for (let i = 0; i < urls.length; i += 8) {
    await Promise.all(urls.slice(i, i + 8).map(async url => {
      try {
        const res = await fetch(url, { cache: 'reload' });
        if (res.ok) await cache.put(url, res);
        else missing.push(url);
      } catch (e) { missing.push(url); }
    }));
  }
  if (strict && missing.length) {
    // Failing the install is deliberate: the browser retries later, which
    // is far better than activating an app that dies offline.
    throw new Error('precache incomplete: ' + missing.join(', '));
  }
  return missing;
}

/* Cache whatever is still missing. Runs on activate and whenever the
   page asks, so a patchy first load repairs itself on the next one. */
async function topUp() {
  const cache = await caches.open(CACHE);
  const missing = [];
  for (const url of ASSETS) {
    if (!(await cache.match(url))) missing.push(url);
  }
  if (missing.length) await fill(cache, missing, false);
  return missing.length;
}

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    await fill(cache, CRITICAL, true);
    await fill(cache, ASSETS.filter(u => !CRITICAL.includes(u)), false);
    await self.skipWaiting();
  })());
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const keys = await caches.keys();
    await Promise.all(keys
      .filter(k => k !== CACHE && k !== VAULT)
      .map(k => caches.delete(k)));
    await self.clients.claim();
    await topUp();
  })());
});

self.addEventListener('message', event => {
  const msg = event.data || {};
  if (msg.type === 'topup') {
    event.waitUntil(topUp().then(n => {
      event.source && event.source.postMessage({ type: 'topup-done', repaired: n });
    }));
  }
  if (msg.type === 'version') {
    event.source && event.source.postMessage({ type: 'version', cache: CACHE });
  }
  if (msg.type === 'skip-waiting') self.skipWaiting();
});

/* ── fetch strategies ───────────────────────────────────────────────
   The app used to be cache-first for everything, which meant a deploy
   only reached a phone if sw.js itself changed — one forgotten build
   step and the installed app was frozen forever. Now freshness does not
   depend on the worker being rebuilt:

     shell  (html/js/css/json)  network-first, cache is the fallback
     images (img/, icons/)      cache-first, refreshed in the background
     rest                       cache-first, then network

   Offline behaviour is unchanged: every branch ends at the cache.     */

const SHELL_RE = /\.(html|js|css|json|webmanifest)$/i;
const IMAGE_RE = /\.(png|jpe?g|webp|svg|gif|avif)$/i;
const NET_TIMEOUT = 3500;

function withTimeout(promise, ms) {
  return Promise.race([
    promise,
    new Promise((_, reject) => setTimeout(() => reject(new Error('slow network')), ms)),
  ]);
}

/** Always try the network; fall back to whatever we cached last time. */
async function networkFirst(req, key) {
  const cache = await caches.open(CACHE);
  try {
    const res = await withTimeout(fetch(req, { cache: 'no-store' }), NET_TIMEOUT);
    if (!res || !res.ok) throw new Error('bad response');
    await cache.put(key || req, res.clone());
    return res;
  } catch (e) {
    const cached = await cache.match(key || req, { ignoreSearch: true });
    if (cached) return cached;
    throw e;
  }
}

/** Paint instantly from cache, quietly pick up a newer copy for next time. */
async function staleWhileRevalidate(req, event) {
  const cache = await caches.open(CACHE);
  const cached = await cache.match(req, { ignoreSearch: true });
  const fresh = fetch(req)
    .then(res => { if (res && res.ok) cache.put(req, res.clone()); return res; })
    .catch(() => null);
  if (cached) {
    // keep the worker alive until the refresh lands, without delaying paint
    try { event.waitUntil(fresh); } catch (e) {}
    return cached;
  }
  const res = await fresh;
  return res || new Response('Offline', { status: 503 });
}

self.addEventListener('fetch', event => {
  const req = event.request;
  if (req.method !== 'GET') return;

  let url;
  try { url = new URL(req.url); } catch (e) { return; }
  if (url.origin !== self.location.origin) return;

  // A launch or reload: this is the one that decides whether the user
  // sees today's version or last month's.
  if (req.mode === 'navigate') {
    event.respondWith((async () => {
      try { return await networkFirst(req, 'index.html'); }
      catch (e) {
        const cached = await caches.match('index.html');
        return cached || new Response('Offline', { status: 503 });
      }
    })());
    return;
  }

  if (SHELL_RE.test(url.pathname)) {
    event.respondWith((async () => {
      try { return await networkFirst(req); }
      catch (e) { return new Response('Offline', { status: 503 }); }
    })());
    return;
  }

  if (IMAGE_RE.test(url.pathname)) {
    event.respondWith(staleWhileRevalidate(req, event));
    return;
  }

  event.respondWith((async () => {
    const cached = await caches.match(req, { ignoreSearch: true });
    if (cached) return cached;
    try {
      const res = await fetch(req);
      if (res.ok) (await caches.open(CACHE)).put(req, res.clone());
      return res;
    } catch (e) {
      return new Response('Offline', { status: 503 });
    }
  })());
});
